graph TD
    %% Public facing components (Next.js in container)
    subgraph Frontend["Public endpoints"]
        F1[Homepage]
        F2[Login]
        F3[Registration]
        F4[Customer Console]
        F5[Admin Login]
        F6[Admin Console]
    end
    
    %% API Services (Python FastAPI in Container)
    subgraph API["API Services"]
        B1[API Gateway]
        B2[User Service]
        B3[Job Service]
        B4[Reporting Service]
        B5[Billing Service]
        B6[Target Service]
    end
    
    %% Relational Data Storage (Postgres managed service on Fly.io)
    subgraph Relational_DB["PostgreSQL"]
        D1[Users]
        D2[Targets]
        D3[Jobs]
        D4[Reports]
        D5[Billing]
        D6[Keycloak Schema]
    end

    %% Timeseries Data Storage (QuestDB deployed in a container)
    subgraph Timeseries_DB["QuestDB"]
        T1[Job logs]
        T2[Job results]
    end   
    
    %% Keycloak Identity Provider
    subgraph Keycloak["Keycloak Auth in Container"]
        K1[OAuth Providers]
        K2[User Authentication]
        K3[Authorization]
        K4[User Federation]
        K5[Admin Console]
    end
    
    %% AI Services
    subgraph AI["AI Services"]
        AI1[Agentic AI nuclei]
        AI2[Agentic AI amass]
        AI3[Agentic AI nmap]
        AI4[Agentic AI zap]
        AI5[Agentic AI Report]
    end
    
    %% Connections Frontend to Keycloak   
    F2 --> K2
    F4 --> K3
    F5 --> K2
    F6 --> K3
    F6 --> K5

    %% Connections Frontends to API Gateway
    F1 --> B1
    F3 --> B1
    F4 --> B1
    F5 --> B1
    F6 --> B1
    
    %% Connections API Gateway to APIs
    B1 --> B2
    B1 --> B3
    B1 --> B4
    B1 --> B5

    %% Connections Job Service to Agentic AIs
    B3 --> AI1 
    B3 --> AI2 
    B3 --> AI3 
    B3 --> AI4 
    B3 --> AI5 

    %% Connections Services to DBs
    AI1 --> T1
    AI1 --> T2
    AI2 --> T1
    AI2 --> T2
    AI3 --> T1
    AI3 --> T2
    AI4 --> T1
    AI4 --> T2
    AI5 --> T1
    AI5 --> T2

    %% Connections APIs to Relation DB
    B2 --> D1
    B3 --> D3
    B4 --> D4
    B5 --> D5
    B6 --> D2
    Keycloak --> D6

    %% Style
    style Frontend fill:#fff,stroke:#000,stroke-width:2px
    style API fill:#E3F7E2,stroke:#000,stroke-width:2px
    style Keycloak fill:#FFD3D1,stroke:#000,stroke-width:2px
    style AI fill:#FFE6CC,stroke:#000,stroke-width:2px